### Site Settings ###
title               : Kaio Colombaroli
description         : >-
                      Engenheiro de IA Generativa | Python | LangChain | OpenAI
baseurl             : ""
repository          : kaiocolombaroli/kaiocolombaroli.github.io
remote_theme        : yousinix/portfolYOU
open_new_tab        : true


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Kaio Colombaroli
  image             : https://ui-avatars.com/api/?name=Kaio+Colombaroli&size=300&background=4f46e5&color=fff
  email             : kaiocolombaroli1@gmail.com
  github            : kaiocolombaroli
  linkedin          : kaiocolombaroli-b1bb64231


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Analytics ###
analytics:
  enabled: false
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - "*.log"
